version: '3'

services:
  help-desk-gui:
    build:
      context: .docker
      dockerfile: Dockerfile
    container_name: help-desk-gui
    hostname: help-desk-gui
    entrypoint: ./.docker/entrypoint.sh
    volumes:
      - .:/home/node/app
      - ./.docker/zsh/powerlevel10k/.p10k.zsh:/home/node/.p10k.zsh:delegated
      - ./.docker/zsh/history:/home/node/zsh:delegated
    ports:
      - '9876:9876'
      - '${PORT}:${PORT}'
    networks:
      - monitor-webrtc-control

networks:
  monitor-webrtc-control:
    name: monitor-webrtc-control-net
    external: true
